FROM node:16.10

# RUN npm install --global yarn

WORKDIR /app

COPY package.json /app/
RUN yarn install

COPY . .

# Generates Prisma artifacts for Prisma Client
RUN ./node_modules/.bin/prisma generate

EXPOSE 9000
EXPOSE 9999

CMD [ "yarn", "debug" ]
