version: "3.7"

networks:
  staw:
    name: staw

services:
  postgres:
    container_name: storage
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - staw
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - staw
    ports:
    - 8080:80

  
  redis:
    container_name: cache
    image: "redis:6.2.6-alpine"
    networks:
      - staw
    ports:
      - "6379:6379"
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    init: true
    container_name: backend
    networks:
      - staw
    ports:
      - "9000:9000"
      - "9999:9999"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres
    environment:
      - CACHE_OAUTH_STATE_URL=redis://cache:6379/1
      - DATABASE_URL=postgresql://postgres:postgres@storage:5432/staw
      - PKCE_AUTHORIZATION_CODE_SECRET=KLvx7XOqw447prLKYcvf5a9GLZj4zD8p+gVW61DgePg=
