### sign-in

POST /sign-up
Host: example.net
Content-Type: application/x-www-form-urlencoded

siteId=super&email=john.doe@super.net


### invite
GET /invite?code=c0ed5fa
Host: super.example.net

### 
GET /invite-fail?reason
Host: super.example.net