FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:16-buster

# Creating non-root user
USER node

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]