### UI Application
GET / 
Host: john.example.net


### API v1


# Healthcheck
GET /api/v1
Host: john.example.net


###
POST /api/v1/sign-in
Host: john.example.net
Content-Type: application/json

{
  "siteId": "john",
  "email": "fupslot@gmail.com"
}